export const personalInfo = {
  name: "Ananya Gupta",
  tagline: "Building technology that translates into meaningful experiences",
  subtitle: "CS (IoT) @ VIT Vellore · CGPA 9.04",
  bio: "I'm a Computer Science student specializing in IoT at VIT Vellore, driven by the belief that the best technology disappears into the experience it creates. I build at the intersection of hardware, software, and human emotion.",
  email: "ananya.gupta@example.com",
  github: "https://github.com/ananyagupta",
  linkedin: "https://linkedin.com/in/ananyagupta",
  location: "VIT Vellore, Tamil Nadu",
};

export const projects = [
  {
    slug: "wireless-gesture-car",
    title: "Wireless Gesture Controlled Car",
    shortTitle: "Gesture Car",
    year: "2024",
    category: "IoT / Hardware",
    tagline: "Where hands become the steering wheel",
    description: "A wireless RC car controlled entirely through hand gestures using accelerometer data, eliminating the need for traditional controllers.",
    problem: "Traditional RC car controllers create a disconnect between the operator and the vehicle. They require learning complex button mappings and don't feel natural or intuitive.",
    approach: "We mapped human hand gestures—tilt angles—to directional commands using an MPU-6050 accelerometer on a glove. The data is transmitted wirelessly via NRF24L01 RF modules at 2.4GHz.",
    tech: ["Arduino Uno", "MPU-6050 Accelerometer", "NRF24L01 RF Module", "L298N Motor Driver", "C++", "I2C Protocol"],
    outcome: "Achieved sub-20ms latency for gesture-to-movement response, 15m wireless range, and intuitive control that takes under 2 minutes to learn.",
    color: "#c8a96e",
    accentColor: "#7c6aff",
    gradient: "from-amber-900/20 to-violet-900/20",
  },
  {
    slug: "railreserve",
    title: "RailReserve",
    shortTitle: "RailReserve",
    year: "2024",
    category: "Full Stack / Systems",
    tagline: "Railway reservations, reimagined",
    description: "A comprehensive railway ticket booking system with real-time seat availability, PNR tracking, and an admin dashboard for train management.",
    problem: "Existing railway booking platforms are notorious for poor UX, slow performance under load, and lack of real-time seat availability—leading to frustration and missed bookings.",
    approach: "Built a normalized relational database schema optimized for concurrent seat reservations with atomic transactions. The frontend provides instant feedback with optimistic UI updates while backend locks prevent double-booking.",
    tech: ["React", "Node.js", "Express", "MySQL", "REST API", "JWT Auth"],
    outcome: "Supports 500+ concurrent users with zero race conditions in seat allocation. Booking flow reduced to 3 steps from the industry standard of 7+.",
    color: "#ff6a6a",
    accentColor: "#c8a96e",
    gradient: "from-red-900/20 to-amber-900/20",
  },
];

export const experience = [
  {
    id: 1,
    role: "Business Development Intern",
    org: "TechStartup",
    period: "2024",
    description: "Drove client acquisition through market analysis and strategic outreach. Collaborated with cross-functional teams to translate technical capabilities into compelling value propositions.",
    tags: ["Strategy", "Client Relations", "Market Research"],
    type: "industry",
  },
  {
    id: 2,
    role: "Vice Chairperson",
    org: "MUN Society, VIT Vellore",
    period: "2023–2024",
    description: "Led a 200+ member society, overseeing conference logistics, delegate training, and committee operations for VIT's flagship international MUN conference.",
    tags: ["Leadership", "Diplomacy", "Event Management"],
    type: "leadership",
  },
  {
    id: 3,
    role: "Under Secretary General",
    org: "VITMUN",
    period: "2023",
    description: "Chaired high-impact committees and moderated complex geopolitical debates. Drafted committee guides and trained junior delegates in diplomatic protocol.",
    tags: ["Public Speaking", "Research", "Mentorship"],
    type: "leadership",
  },
  {
    id: 4,
    role: "Design Core Member",
    org: "Technical Club, VIT",
    period: "2022–2023",
    description: "Created visual identities and motion graphics for technical events. Bridged design thinking with engineering—bringing aesthetic rigor to technical communication.",
    tags: ["UI/UX", "Branding", "Motion Design"],
    type: "creative",
  },
];

export const achievements = [
  {
    id: 1,
    title: "Women Achiever of the Year",
    subtitle: "2025–26 · VIT Vellore",
    description: "Recognized for exceptional contributions to technology, leadership, and community building across academic and extracurricular domains.",
    icon: "★",
    color: "#c8a96e",
    year: "2025",
    weight: "hero",
  },
  {
    id: 2,
    title: "Best Delegate",
    subtitle: "VITMUN 2023 · UNSC Committee",
    description: "Awarded for exemplary research, diplomatic argumentation, and consensus-building in the United Nations Security Council simulation.",
    icon: "◆",
    color: "#7c6aff",
    year: "2023",
    weight: "major",
  },
  {
    id: 3,
    title: "Achievers List",
    subtitle: "VIT Vellore · Academic Excellence",
    description: "Placed on the institutional Achievers List for maintaining a CGPA of 9.04 while actively contributing to extracurricular excellence.",
    icon: "●",
    color: "#4ecdc4",
    year: "2024",
    weight: "major",
  },
  {
    id: 4,
    title: "High Commendation",
    subtitle: "SIRMUN 2023",
    description: "Awarded for outstanding performance in committee deliberations at the SRM Institute's international MUN conference.",
    icon: "▲",
    color: "#ff6a6a",
    year: "2023",
    weight: "minor",
  },
];

export const skills = [
  { name: "C / C++", level: 88, category: "languages" },
  { name: "Python", level: 82, category: "languages" },
  { name: "JavaScript", level: 80, category: "languages" },
  { name: "SQL", level: 75, category: "languages" },
  { name: "React", level: 78, category: "frontend" },
  { name: "Node.js", level: 72, category: "backend" },
  { name: "Arduino", level: 90, category: "iot" },
  { name: "IoT Protocols", level: 85, category: "iot" },
  { name: "DBMS", level: 80, category: "systems" },
  { name: "Computer Networks", level: 76, category: "systems" },
  { name: "UI/UX Design", level: 70, category: "design" },
  { name: "Leadership", level: 92, category: "soft" },
];

export const navItems = ["Home", "About", "Projects", "Experience", "Achievements", "Contact"];
